
name: Multiple jobs

on: [push]

jobs: 
  job_1:
    runs-on: ubuntu-latest
    steps: 
    - name: Checkout
      uses: actions/checkout@v4
    - name: Install Cowsay
      run: sudo apt-get install cowsay -y

    - name: Add permission 
      run: sudo chmod u+x ./cowsay_script.sh
  
  job_2:
    name: Test Job
    runs-on: ubuntu-latest
    steps:
    - name: Sleep for 10 secs
      run: sleep 10
    - name: Test files exist
      run: grep -i "dragon" dragon.txt

  job_3: 
    name: Deploy Job
    runs-on: ubuntu-latest
    steps:
    - name: Read file
      run: cat dragon.txt
    - name: Deploy 
      run: echo "Deploying !!"