name: My workflow test

on: [push]

jobs: 
    first_job:
      runs-on: ubuntu-latest
    
      steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Welcome Message
        run: echo "first Github actions certification example"
      
      - name: List files
        run: ls -a

      - name: Read files
        run: cat README.md