name: Multiple jobs

on: [push]

jobs: 
  job_1:
    runs-on: ubuntu-latest
    steps: 
    - name: Checkout
      uses: actions/checkout@v4
    - name: Install Cowsay
      run: sudo apt-get install cowsay -y

    - name: Add permission 
      run: sudo chmod u+x ./cowsay_script.sh
    - name: Upload 
      uses: actions/upload-artifact@v4
      with:
        name: Dragon_text
        path: ./dragon.txt

  
  job_2:
    name: Test Job
    needs: job_1
    runs-on: ubuntu-latest
    steps:
    - name: Sleep for 10 secs
      run: sleep 10
    - name: Download Artifact
      uses: actions/download-artifact@v4
      with:
       name: Dragon_text

    - name: Test files exist
      run: grep -i "dragon" dragon.txt

  job_3: 
    name: Deploy Job
    needs: job_2
    runs-on: ubuntu-latest
    steps:
    - name: Download Artifact
      uses: actions/download-artifact@v4
      with:
         name: Dragon_text
    
    - name: Read file
      run: cat dragon.txt

    - name: Deploy 
      run: echo "Deploying !!"