name: My workflow test

on: [push]

jobs: 
    first_job:
      runs-on: ubuntu-latest
    
      steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Welcome Message, List and Read files
        run: | 
          echo "first Github actions certification example"
          ls -ltra
     